### ISSUE TITLE
".\" added to table name in SQLITE database file

### ISSUE THREAD

**Issue by joel0977** [simonw/csvs-to-sqlite#31]
Hello Simon, thanks a lot for your great tool and sharing.

I am using it to convert a bunch of csv files in a folder. i get a .db file as output; anyhow my table names are marked with a ".\"chars which do not allow me to perform further sqlite queries...could you please advice me how to avoid this issue?
Below my cmd input and output:
C:~Documents\Profesional\2018-02-15>csvs-to-sqlite C:~Documents\Profesional\2018-02-15 output.db
extract_columns=()
Loaded 4 dataframes
c:\users\joel0\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\generic.py:1362: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)
Created output.db from 4 CSV files

thanks in advance

**Comment by simonw** [comment]
You can run queries against columns with dots in their names by quoting them, for example:

    select * from [my.table.with.dots];

**Comment by simonw** [comment]
Here's a demo: https://csvs-to-sqlite-date-demo.now.sh/antiquities-317d506?sql=select+*+from+[actions.under.antiquities.act]

**Comment by MaffooClock** [comment]
When I read the subject of the issue, I thought we'd be talking about how this tool inadvertently added the current directory to the table names (e.g. ".\TableName" for Windows, "./TableName" for *nix).

When I ran the tool against a blob of CSV files (/path/to/files/*.csv), all of the tables were named as expected.  But when I ran the tool against a directory (/path/to/files), all of the table names are preceeded with "./".

Seems like a bug to me.

**Comment by RobAley** [comment]
I think this is a bug too, @simonw , on Windows at least. 
Wildcards don't work, so if I have test1.csv and test2.csv in a folder called input, I can't do :
`csvs-to-sqlite input\*.csv output.db`
as it complains "input\*.csv" does not exist. I can do :
`csvs-to-sqlite input output.db`
and it will correctly get all csv files in the "input" folder. However the resulting tables will be called ".\test1" and ".\test2" rather than just "test1" and "test2".
